#!/bin/bash

export JAVA_TOOL_OPTIONS="-javaagent:/opt/opentelemetry-javaagent.jar ${JAVA_TOOL_OPTIONS}"

if [[ $OTEL_RESOURCE_ATTRIBUTES != *"service.name="* ]]; then
  export OTEL_RESOURCE_ATTRIBUTES="service.name=${AWS_LAMBDA_FUNCTION_NAME},${OTEL_RESOURCE_ATTRIBUTES}"
fi

export OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT=2000

if [ -z "$OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED" ]; then
    export OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED="false"
fi

if [ -z "$OTEL_INSTRUMENTATION_AWS_LAMBDA_ENABLED" ]; then
    export OTEL_INSTRUMENTATION_AWS_LAMBDA_ENABLED="true"
fi

if [ -z "$OTEL_INSTRUMENTATION_AWS_SDK_ENABLED" ]; then
    export OTEL_INSTRUMENTATION_AWS_SDK_ENABLED="true"
fi

CMD="$(echo "$@" | sed 's/-Xshare:on/-Xshare:auto/g')"

exec $CMD
