name: Publish Python

on: 
  push:
  # workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Actually publish or just test?'
    #     type: environment
    #     required: true
    #     default: test

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release') || inputs.environment == 'test' }}
    # environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        path: ./opentelemetry-python-contrib
        repository: coralogix/opentelemetry-python-contrib
        ref: refs/heads/coralogix-python-dev
        ssh-key: ${{ secrets.OPENTELEMETRY_CI_GITHUB_KEY }}
    - name: build opentelemetry-instrumentation-aws-lambda
      working-directory: ./python/sample-apps/otel
      run: pip3 wheel -e ../../../opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-aws-lambda
    - name: build opentelemetry-instrumentation-botocore
      working-directory: ./python/sample-apps/otel
      run: pip3 wheel -e ../../../opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-botocore
    - name: build layer
      working-directory: ./python/sample-apps/otel
      run: |
        mkdir -p ./build
        python3 -m pip install -r otel_sdk/requirements.txt -t ./build/python
        python3 -m pip install -r otel_sdk/requirements-nodeps.txt -t ./build/tmp --no-deps
        cp -r ./build/tmp/* ./build/python/
        rm -rf ./build/tmp
        mv otel_sdk/otel_wrapper.py ./build/python
        mv otel_sdk/otel-instrument ./build
        chmod 755 ./build/otel-instrument
        rm -rf ./build/python/boto*
        rm -rf ./build/python/urllib3*
    - name: package layer
      working-directory: ./python/sample-apps/otel/build
      run: zip -r layer.zip otel-instrument python
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: layer.zip
        path: ./python/sample-apps/otel/build/layer.zip
        if-no-files-found: error
        retention-days: 1

    # - uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ vars.SAR_AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.SAR_AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ vars.SAR_AWS_DEFAULT_REGION }}